import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import WidgetContainer from "./widgets/widget";
import "./globals.css";
import clsx from "clsx";
import WaveContainer from "./components/Wavify/Wavify";
import Stars from "./components/Stars/Stars";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
        className={`${montserrat.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className={clsx("relative min-h-full flex flex-col transition-colors duration-300 ease-in-out bg-base-300 text-base-content z-0", montserrat.variable)}>
            {children}
          <Stars />
          <WaveContainer />
          <WidgetContainer />
        </body>
    </html>
  );
}
